# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # This setting enables warnings. It's recommended, but in some cases may
  # be too noisy due to issues in dependencies.
  config.warnings = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end

  # 🔴 **「0 examples」不是通過。**
  #
  # 2026-08-15 實例：`spec/fixtures/ci_violations/**` 底下為了餵 CI 檢查器而放的
  # 腳手架檔案叫 `money_spec.rb`，被 rspec 的預設 pattern 撿走，
  # **整個套件從 233 examples 變成 0**。當時它是 exit 非零（載入期炸了）所以看得出來，
  # 但只要那些檔案是「合法但什麼都不做的 Ruby」，就會是 **0 examples ＋ exit 0**
  # ——CI 全綠，而**一條測試都沒跑**。
  #
  # 這與本專案反覆踩到的形態是同一個：**回報成功但什麼都沒做**
  # （lint 規則的六種漏看、跨租戶 destroy 刪 0 列、建店缺 publication）。
  # ⇒ 用一個下限守住。數字刻意設得很低（只防「整包沒跑」，不防「少跑幾條」），
  #   這樣它不需要隨著新增測試而維護。
  MINIMUM_EXAMPLES = 50

  # 「這次是不是在跑全套」的判準＝**命令列完全沒帶參數**（`bundle exec rspec`）。
  #
  # 🔴 第一版拿「載入的 spec 檔數 < 5」當「使用者在跑子集」——**判斷反了**：
  # 「載入的檔案很少」正是我要抓的那個 bug 的**症狀**，不是它的反例。
  # 結果就是 pattern 壞掉時檔案數變 0，守衛反而被自己的條件跳過。
  # （實測：把 exclude-pattern 改成排除全部 ⇒ 0 examples 而守衛沒開火。）
  #
  # `RSpec.configuration.files_or_directories_to_run` 在 rspec-core 3.13 上是 private，
  # 所以改用 **ARGV**：跑子集一定會帶路徑或 `-e`／`--tag`。
  #
  # ⚠️ 判準**不是** `ARGV.empty?`——`ARGV` 含 RSpec 自己的 flag
  # （實測：`bundle exec rspec --no-color` 的 ARGV 是 `["--no-color"]`），
  # 用 `empty?` 會讓「帶任何 flag 的全套執行」都跳過守衛，而那是我驗證時的常用形態。
  SUBSET_MARKERS = %w[-e --example -t --tag].freeze
  FULL_SUITE_RUN = ARGV.none? do |arg|
    arg.start_with?("spec/", "./spec/", "spec\\") || SUBSET_MARKERS.include?(arg)
  end

  config.after(:suite) do
    # 🔴 **只在「跑全套」時生效**。第一版沒有這個條件，於是
    # `bundle exec rspec spec/models/money_spec.rb`（22 examples）也被擋下來
    # ——一個讓「單跑一個檔案」永遠失敗的守衛，會在第一天就被人拿掉。
    # 守衛要活得下來，它就不能妨礙日常操作。
    next unless FULL_SUITE_RUN

    count = RSpec.world.example_count
    next if count >= MINIMUM_EXAMPLES

    abort <<~MESSAGE
      ::error::只跑了 #{count} 個 example（下限 #{MINIMUM_EXAMPLES}）——這不是通過，是套件根本沒載入。
        最可能的原因：spec 檔案的 pattern 被改壞，或有非 spec 的檔案叫 `*_spec.rb`
        而讓 rspec 在載入期就停下來（見 .rspec 的 --exclude-pattern）。
    MESSAGE
  end
end
